### ISSUE TITLE
呵呵🌝

### ISSUE THREAD

**Issue by xianquu** [serverbread/SB_web#9]
我上github 怎么了 github是美国🇺🇸的 言论自由不知道吗🌝😅我就痛恨@shenmo7192 (欧阳云睿) 怎么了🌝你们不知道国产垃圾linux系统 以及欧阳云睿制作的垃圾“星火”病毒商店 有多垃圾，我剿灭掉那个商店，就是正义行动，美国肯定支持我 你们向github投诉也没用🌝

**Comment by serverbread** [comment]
> 我上github 怎么了 github是美国🇺🇸的 言论自由不知道吗🌝😅我就痛恨@shenmo7192 (欧阳云睿) 怎么了🌝你们不知道国产垃圾linux系统 以及欧阳云睿制作的垃圾“星火”病毒商店 有多垃圾，我剿灭掉那个商店，就是正义行动，美国肯定支持我 你们向github投诉也没用🌝

傻逼。

**Comment by serverbread** [comment]
> 我上github 怎么了 github是美国🇺🇸的 言论自由不知道吗🌝😅我就痛恨@shenmo7192 (欧阳云睿) 怎么了🌝你们不知道国产垃圾linux系统 以及欧阳云睿制作的垃圾“星火”病毒商店 有多垃圾，我剿灭掉那个商店，就是正义行动，美国肯定支持我 你们向github投诉也没用🌝

国内的开源社区这么差，环境这么烂，不尊重开源协议+抄袭泛滥就是你们这群**弱智**搞的😅。

之前是没见过真傻逼，这回真见到了😋。

看你repo列表就知道成分了，啥也不会的臭脚本小子。

得，孝敬你的美国爹去吧，罕见。

**Comment by xianquu** [comment]
# 你才是神经病🌝

**Comment by xianquu** [comment]
> > 我上github 怎么了 github是美国🇺🇸的 言论自由不知道吗🌝😅我就痛恨@shenmo7192 (欧阳云睿) 怎么了🌝你们不知道国产垃圾linux系统 以及欧阳云睿制作的垃圾“星火”病毒商店 有多垃圾，我剿灭掉那个商店，就是正义行动，美国肯定支持我 你们向github投诉也没用🌝
> 
> 国内的开源社区这么差，环境这么烂，不尊重开源协议+抄袭泛滥就是你们这群**弱智**搞的😅。
> 
> 之前是没见过真傻逼，这回真见到了😋。
> 
> 看你repo列表就知道成分了，只不过是啥也不会的**垃圾脚本小子**。
> 
> 得，**孝敬**你的**美国爹**去吧，**罕见**！
> 
> 给你block了，**臭 傻 逼**。

# 胡说八道一通还加粗几个字 有什么本事啊🌝我会go go可不是“脚本”🌝

**Comment by xianquu** [comment]
你才是脚步小子呢🌝
![IMG_3319](https://github.com/serverbread/SB_web/assets/160004827/b63442e0-85a6-4697-a947-b352a9d11cd6)
